# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Extract marks and metadata from CVR JSON
#'
#' @param sessions  CVR JSON
#' @param max_marks Maximum number of vote choice that JSON could contain
#' @return dataframe containing the extracted vote choices and meta data
extract_marks <- function(sessions, max_marks) {
    .Call(`_dominionCVR_extract_marks`, sessions, max_marks)
}

